name: Testing load balancing Cypress E2E tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
      runners:
        type: number
        description: Number of runners to use for parallelization
        required: false
        default: 3
      debug:
        type: boolean
        description: Enables debugging on the job and on the cypress-load-balancer script.

env:
  runners: ${{ inputs.runners || secrets.CYPRESS_LOAD_BALANCER_RUNNERS || 3 }}
  CYPRESS_LOAD_BALANCER_DEBUG: ${{ inputs.debug || false }}

jobs:
  get_specs:
    runs-on: ubuntu-22.04
    outputs:
      e2e_specs: ${{ steps.balance.outputs.cypressLoadBalancerSpecs }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: ./actions/balance
        id: balance
        with:
          runners: ${{ env.runners }}
          testing-type: e2e
