#name: Tests

#jobs:
#  mocha:
#    name: Unit tests
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-node@v4
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#      - run: |
#          yarn install
#          yarn run build
#          yarn run mocha

name: 'Trying something out'
on:
  pull_request:

env:
  PERSON_TO_GREET: 'Leon S. Kennedy'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: node script.js
